### ISSUE TITLE
where can we find new data for 3.21?

### ISSUE THREAD

**Issue by NomaratheF** [KeshHere/TimelessJewelData#1]
pob already has updated timeless finder. where did they get the data? or is it posiible to parse data from pob?

i see binary files in ...\TimelessJewelData but how to convert them to your data files?

**Comment by KeshHere** [comment]
Hey sorry for kinda late reply, pob has its own method to generate the data by itself & for the good news I am updating the CSVs for 3.21 right now, should be ready about in an hour. If you want to ask more questions about pob, it will be best suited to ask them about how they generate such data.

**Comment by NomaratheF** [comment]
sorry, i thought you take data from pob files

**Comment by KeshHere** [comment]
This time yes I did use PoB's LuTs [Look up tables] available here https://github.com/Regisle/TimelessJewelData
Glorious Vanity LuT is tricky one to work with, other 4 are fairly simple to figure out.
